config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#index', as: 'home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :sessions, only: %i[create destroy], param: :user_token
      resources :lists, only: %i[create index destroy update], param: :user_token
      resources :songs, only: %i[create index destroy update], param: :user_token
      resources :lists_users, only: %i[create show destroy update], param: :user_token
    end
  end

  resources :songs, only: %i[index destroy]
  resources :lists, only: :destroy
  resources :search, only: :index
  resources :add_lists, only: :create
  resources :style_ratings, only: :create
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
  belongs_to :owner, class_name: User, foreign_key: 'user_id'
  has_many :songs, dependent: :destroy
  has_and_belongs_to_many :users
  validate :user_id_exists

  scope :available_users_lists, (lambda do |user_id|
    left_outer_joins(:users).where(
      '(lists.user_id = :user_id or lists_users.user_id = :user_id) OR is_private = :is_private',
      { user_id: user_id, is_private: false }
    )
  end)

  def user_id_exists
    errors.add(:user_id, 'User does not exist.') unless User.find_by(id: user_id)
  end

  def copy_songs(old_list)
    old_list.songs.each do |song|
      new_song = song.dup
      new_song.attributes = { id: nil, list_id: id }
      new_song.save
    end
  end

  def as_json(options = {})
    super(options.reverse_merge(only: %i[name description is_private]))
  end
end

app/controllers/api/v1/lists_controller.rb
class Api::V1::ListsController < Api::ApiController
  before_action :set_user_by_token
  before_action :find_list, only: %i[update destroy]

  def index
    lists = List.where(user_id: @current_user.id)
    authorize lists
    unless lists.blank?
      render json: lists, status: 200
    else
      render json: { message: 'List not found' }, status: 404
    end
  end

  def create
    list = @current_user.owned_lists.new(list_params)
    authorize list
    if list.save
      render json: list, status: 201
    else
      render json: { message: 'Error with save' }, status: 400
    end
  end

  def update
    authorize @list
    if @list.update(list_params)
      render json: @list, status: 200
    else
      render json: { message: 'Error with update' }, status: 400
    end
  end

  def destroy
    authorize @list
    if @list.destroy
      render json: { message: 'Deletion completed successfully' }, status: 200
    else
      render json: { message: 'Error with deleted' }, status: 400
    end
  end

  private

  def find_list
    @list = List.find_by(id: params[:list][:id])
    render json: { message: 'List not found' }, status: 404 unless @list
  end

  def list_params
    params.require(:list).permit(:name, :description, :is_private)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :retrieve_list, only: :destroy

  def index
    @lists =
      case params[:status]
      when 'private'
        Kaminari.paginate_array(current_user.owned_lists.where(is_private: true)
          .sort_by { |e| e[:created_at] }.reverse).page(params[:page]).per(8)
      when 'only'
        Kaminari.paginate_array(current_user.owned_lists
          .sort_by { |e| e[:created_at] }.reverse).page(params[:page]).per(8)
      else
        Kaminari.paginate_array((current_user.owned_lists + current_user.lists)
          .sort_by { |e| e[:created_at] }.reverse).page(params[:page]).per(8)
      end
    @lists_public = List.where(is_private: false).where.not(user_id: current_user.id).page(params[:page]).per(8)
    @styles = Style.all
    respond_to do |format|
      format.html {}
      format.json { render json: { html: render_to_string(partial: 'lists.slim', layout: false) } }
    end
  end

  def destroy
    authorize @list
    if @list.destroy
      redirect_to home_path, notice: 'The deletion was successful'
    else
      redirect_to home_path, notice: 'The deletion was unsuccessful'
    end
  end

  private

  def retrieve_list
    @list = List.find_by(id: params[:id])
    redirect_to(home_path, notice: 'List is not found.') && return if @list.blank?
  end
end

app/views/lists/_lists.slim
- unless @lists.blank?
  table.lists
    thead
      tr
        th Name
    tbody
      - @lists.each do |list|
        tr.tr_height
          td
            = link_to list.name, songs_path(list_id: list.id)
          - if list.user_id == current_user.id
            td
              = link_to list_path(id: list.id), {method: :delete, data: { confirm: "Are you sure?" }, remote: true}  do
                i.delete.rightlog
- else
  h4 No lists

app/views/lists/_lists_public.slim
- unless @lists_public.blank?
  table
    thead
      tr
        th Name
    tbody
      - @lists_public.each do |list|
        tr
          td= link_to list.name, songs_path(list_id: list.id)
          td.td_width
          td
            = link_to 'Add to yours?', add_lists_path(list), {method: :post, data: { confirm: "Are you sure?" }}
- else
  h4 No lists

app/views/lists/index.slim
.nav.navbar-nav.navbar-fixed-left.navbar-left.left-board
  h3 My lists:
  = radio_button_tag(:my, "all", true, class: 'filter_lists', data: { key: 'all' })
  = label_tag "my_all", "All my lists"
  br/
  = radio_button_tag(:my, "private", false, class: 'filter_lists', data: { key: 'private' })
  = label_tag "my_private", "Without my public"
  br/
  = radio_button_tag(:my, "only", false, class: 'filter_lists', data: { key: 'only' })
  = label_tag "my_only", "Without available"
  br/
  #lists
    = render 'lists'
  br/
  - if @lists
    = paginate @lists
  br/
.nav.navbar-nav.navbar-fixed.center-graph
  = line_chart @styles.map { |goal|                                                   \
        {name: goal.name, data: goal.owned_ratings.group_by_month(:created_at).count} \
    }                                                                                 
.nav.navbar-nav.navbar-fixed-right.navbar-right.right-board
  h3 Other public user lists:
  #lists
    = render 'lists_public'
  br/
  - if @lists_public
    = paginate @lists_public
  br/