config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#index', as: 'home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :sessions, only: %i[create destroy], param: :user_token
      resources :lists, only: %i[create index destroy update], param: :user_token
      resources :songs, only: %i[create index destroy update], param: :user_token
      resources :lists_users, only: %i[create show destroy update], param: :user_token
    end
  end

  resources :songs, only: %i[index destroy]
  resources :lists, only: :destroy
  resources :search, only: :index
  resources :add_lists, only: :create
  resources :style_ratings, only: :create
end

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title FavoriteSongs
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "//www.google.com/jsapi"

  body
    header.navbar.navbar-inverse
      .container
        - if current_user
          .nav.navbar-nav.left
            = link_to 'FavoriteSongs', home_path, id: "logo"
          .center3
            = link_to 'Search', search_index_path, id: "logo"
            nav
              ul.nav.navbar-nav.navbar-right.navbar-right-new
                = link_to destroy_user_session_path, {method: :delete} do
                  i.logout.rightlog
        - else
          .nav.navbar-nav.center3
            = link_to 'FavoriteSongs', home_path, id: "logo"
    .container
      - if notice
        p.alert.alert-success= notice.html_safe
      - if alert
        p.alert.alert-danger= alert
    = yield